#pragma config(Motor, port2, collector, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor, port3, dumpdump, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor, port4, driverleft, tmotorVex393_MC29, openLoop)
#pragma config(Motor, port5, driverright, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void main()
{
}