#pragma config(Sensor, in1, sharp_front_top, sensorAnalog)
#pragma config(Sensor, in2, sharp_front_bottom_l, sensorAnalog)
#pragma config(Sensor, in3, sharp_front_bottom_r, sensorAnalog)
#pragma config(Sensor, in4, sharp_short, sensorAnalog)
#pragma config(Sensor, in8, compass_power, sensorNone)
#pragma config(Sensor, dgtl1, compass1, sensorDigitalIn)
#pragma config(Sensor, dgtl2, compass2, sensorDigitalIn)
#pragma config(Sensor, dgtl3, compass3, sensorDigitalIn)
#pragma config(Sensor, dgtl4, compass4, sensorDigitalIn)
#pragma config(Sensor, dgtl5, home_limit_l, sensorDigitalIn)
#pragma config(Sensor, dgtl6, home_limit_r, sensorDigitalIn)
#pragma config(Sensor, dgtl7, ball_dispense_1, sensorDigitalIn)
#pragma config(Sensor, dgtl8, ball_dispense_2, sensorDigitalIn)
#pragma config(Sensor, dgtl9, front_l_line, sensorDigitalIn)
#pragma config(Sensor, dgtl10, front_r_line, sensorDigitalIn)
#pragma config(Sensor, dgtl11, back_l_line, sensorDigitalIn)
#pragma config(Sensor, dgtl12, back_r_line, sensorDigitalIn)
#pragma config(Motor, port1, left_driver, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor, port2, roller_driver, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor, port3, ball_dispense_driver, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor, port10, right_driver, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void main(){
    while(1){
        if(!starting_procedure()==1){
            while(!spin_search()){
                if(move_forward() == 1){
                    break; 
            }
        } 
        while(!collect_ball()){
            while(!spin_search()){
                if(move_forward() == 1){
                    break; 
                }
            }
        }
        while (go_back_origin()){}
        while (dispense_ball()){}
    }
}