#pragma config(Sensor, in5,    sharp_front_bottom_r , sensorAnalog)
#pragma config(Sensor, in2,    sharp_front_top, sensorAnalog)
#pragma config(Sensor, in1,    sharp_front_bottom_l, sensorAnalog)
#pragma config(Sensor, in4,    sharp_short,    sensorAnalog)
#pragma config(Sensor, in8,    compass_power,  sensorNone)
#pragma config(Sensor, dgtl1,  compass1,       sensorDigitalIn)
#pragma config(Sensor, dgtl2,  compass2,       sensorDigitalIn)
#pragma config(Sensor, dgtl3,  compass3,       sensorDigitalIn)
#pragma config(Sensor, dgtl4,  compass4,       sensorDigitalIn)
#pragma config(Sensor, dgtl5,  home_limit_l,   sensorDigitalIn)
#pragma config(Sensor, dgtl6,  home_limit_r,   sensorDigitalIn)
#pragma config(Sensor, dgtl7,  ball_dispense_1, sensorDigitalIn)
#pragma config(Sensor, dgtl8,  ball_dispense_2, sensorDigitalIn)
#pragma config(Sensor, dgtl9,  front_l_line,   sensorDigitalIn)
#pragma config(Sensor, dgtl10, front_r_line,   sensorDigitalIn)
#pragma config(Sensor, dgtl11, back_l_line,    sensorDigitalIn)
#pragma config(Sensor, dgtl12, back_r_line,    sensorDigitalIn)
#pragma config(Motor,  port9,           ball_dispense_driver, tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           left_driver,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           right_driver,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port2,           roller_driver, tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "helper_function.h"
#include "sensor_output.h"
const float BOTTOM_DIST_THRES = 550;
const float TOP_DIST_THRES = 33.12;
const int BALL_FOUND = 1;
const int BALL_NOT_FOUND = 0;
int distancel;
int distancer;

task main(){
	while(1){
distancel = SensorValue(sharp_front_bottom_l);
distancer = SensorValue(sharp_front_bottom_r);
writeDebugStreamLine("intl %d", distancel);
writeDebugStreamLine("intr %d", distancer);
sleep(500);
}
}
